version: '3.5'
services:
  server:
    container_name: nodeapp2
    build: .
    # command: npm run build
    # command: node app.js
    command: npm run dev
    volumes:
      - ./src/:/app
      - /app/node_modules
    ports:
      - 5002:3000
    # depends_on:
    environment:
      PORT: 3000
      NAME: "Gus"
    restart: always

