version: '3.5'
services:
  server:
    container_name: nodeapp
    build: .
    # command: npm run build
    # command: node app.js
    command: npm run dev
    volumes:
      - ./src/:/app
      - /app/node_modules
    ports:
      - 5001:3000
    # depends_on:
    environment:
      PORT: 3000
      NAME: "Adam"
    restart: always


    # docker-compose -f docker-compose1.yml -f docker-compose2.yml up --build
