version: '3.5'
services:
  server:
    container_name: simple
    build: .
    # command: npm run build
    # command: node app.js
    command: npm run dev
    volumes:
      - ./src/:/app
      - /app/node_modules
    ports:
      - 8080:3000
    # depends_on:
    environment:
      PORT: 3000
    restart: always

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
      # network: host
    container_name: app-nginx
    restart: always
    # ports:
    #   - "80:80"
    #   - "443:443"
    volumes:
      - ./nginx-docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server

    # docker-compose -f docker-compose1.yml -f docker-compose2.yml up --build
